### ISSUE TITLE
Reading existing checklists

### ISSUE THREAD

**Issue by djl197** [sarumont/py-trello#115]
I have a checklist on a card in Trello.
If I use the fetch_checklists() function card.fetch_checklists() - I get the following error:
Traceback (most recent call last):
  File "./queue_sorter.py", line 36, in <module>
    checklists = request_list.list_cards()[0].fetch_checklists()
  File "/usr/local/lib/python2.7/dist-packages/trello/card.py", line 176, in fetch_checklists
    checklists.append(Checklist(self.client, self.checked, cl,
AttributeError: 'Card' object has no attribute 'checked'

I can use py-trello to create the checklist, I just cant seem to read back the checklist values in a different python script.
Any ideas what I am doing wrong?

**Comment by djl197** [comment]
Doh!
My fault, had not realised that I needed to do card.fetch(eager=True) before calling fetch_checklists().
All working now :-)
