### ISSUE TITLE
Errors on card dates

### ISSUE THREAD

**Issue by adlermedrado** [sarumont/py-trello#183]
```
create_date = {str} 'Traceback (most recent call last):\n  File "/home/adler/pycharm/helpers/pydev/_pydevd_bundle/pydevd_resolver.py", line 197, in _getPyDictionary\n    attr = getattr(var, n)\n  File "/home/adler/.pyenv/versions/trello/lib/python3.6/site-packages/trello/card.py
created_date = {str} 'Traceback (most recent call last):\n  File "/home/adler/pycharm/helpers/pydev/_pydevd_bundle/pydevd_resolver.py", line 197, in _getPyDictionary\n    attr = getattr(var, n)\n  File "/home/adler/.pyenv/versions/trello/lib/python3.6/site-packages/trello/card.py
```

**Comment by sgaynetdinov** [comment]
Hello, show more code

**Comment by sgaynetdinov** [comment]
@adlermedrado try it use `Card.card_created_date`
