### ISSUE TITLE
wrong syntax traceback on a new version 0.11

### ISSUE THREAD

**Issue by alexxa** [sarumont/py-trello#244]
```
Traceback (most recent call last):
  File "scripts/trello_requirements.py", line 6, in <module>
    from trello import TrelloClient
  File "/usr/lib/python2.7/site-packages/trello/__init__.py", line 11, in <module>
    from trello.trelloclient import *
  File "/usr/lib/python2.7/site-packages/trello/trelloclient.py", line 391
    self.fetch_json(f'members/me/boardStars/{star.id}', http_method='DELETE')
                                                     ^
SyntaxError: invalid syntax

```

**Comment by Thingable** [comment]
F-strings were not implemented until python 3.6 and it looks like you are using 2.7. It could be backwards compatible using .format() instead. I was the one who implemented this, but I can’t make the fix until later tonight when I make it home.

**Comment by alexxa** [comment]
No rush =) thanks @Thingable

**Comment by sarumont** [comment]
Merged @Thingable's PR and pushed up to PyPi in `0.11.1`. Thanks!
