### ISSUE TITLE
Failing tests

### ISSUE THREAD

**Issue by JulienPalard** [sarumont/py-trello#65]
o/

I just tried to ran the tests after setting up my OAUTH like readme told me, and got:

```
$ PYTHONPATH=. python test/test_trello.py
F.....EEE.EFF
======================================================================
ERROR: test40_add_card (__main__.TrelloClientTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_trello.py", line 118, in test40_add_card
    if not card:
UnboundLocalError: local variable 'card' referenced before assignment

======================================================================
ERROR: test41_add_card (__main__.TrelloClientTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_trello.py", line 145, in test41_add_card
    if not card:
UnboundLocalError: local variable 'card' referenced before assignment

======================================================================
ERROR: test42_add_card_with_comments (__main__.TrelloClientTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_trello.py", line 176, in test42_add_card_with_comments
    if not card:
UnboundLocalError: local variable 'card' referenced before assignment

======================================================================
ERROR: test51_fetch_cards (__main__.TrelloClientTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_trello.py", line 89, in test51_fetch_cards
    self.assertIsInstance(c.date_last_activity, datetime, msg='date not provided')
  File "/usr/lib/python2.7/unittest/case.py", line 968, in assertIsInstance
    if not isinstance(obj, cls):
TypeError: isinstance() arg 2 must be a class, type, or tuple of classes and types

======================================================================
FAIL: test01_list_boards (__main__.TrelloClientTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_trello.py", line 21, in test01_list_boards
    int(os.environ['TRELLO_TEST_BOARD_COUNT']))
AssertionError: 2 != 1

======================================================================
FAIL: test52_get_cards (__main__.TrelloClientTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_trello.py", line 182, in test52_get_cards
    self.assertEquals(len(boards), 1, msg="Test board not found")
AssertionError: Test board not found

======================================================================
FAIL: test60_delete_cards (__main__.TrelloClientTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_trello.py", line 201, in test60_delete_cards
    self.assertEquals(len(boards), 1, msg="Test board not found")
AssertionError: Test board not found

----------------------------------------------------------------------
Ran 13 tests in 5.341s

FAILED (failures=3, errors=4)
```

**Comment by 211217613** [comment]
for this error 
```
Traceback (most recent call last):
  File "test/test_trello.py", line 21, in test01_list_boards
    int(os.environ['TRELLO_TEST_BOARD_COUNT']))
AssertionError: 2 != 1
```
I would just set my env variable TRELLO_TEST_BOARD_COUNT to 2.
In ubuntu I would do: ```  TRELLO_TEST_BOARD_COUNT=2 ``` then ```export TRELLO_TEST_BOARD_COUNT ```
